alias d="docker"
alias dma="docker-machine"
alias dco="docker-compose"
alias dim="docker images"
alias dst="docker start"
alias dsp="docker stop"

alias dps="docker ps"
alias dpsa="docker ps -a"
alias drm="docker rm"
alias drmi="docker rmi"
