alias d="docker"
alias dma="docker-machine"
alias sdma="eval $(docker-machine env)"
alias dco="docker-compose"
alias dim="docker images"
alias ds="docker start"
alias dst="docker stop"

alias dps="docker ps"
alias dpsa="docker ps -a"
alias drm="docker rm"
alias drmi="docker rmi"
