alias codecept="./vendor/bin/codecept"
alias phpunit="./vendor/bin/phpunit"
alias venv="virtualenv"
alias venva="source bin/activate"
alias art="php artisan"
alias pipupdate="pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U"
alias gf="git fetch"
alias gpp="git push && git push"
alias godev="cd ~/Development"

